#!/bin/bash
# Copyright 2024 Viel Losero.
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) && CWD=$(pwd)
# make temp dir
TMP_DIR=/tmp/HugeSlackBuilds
[[ ! -d $TMP_DIR ]] && mkdir -vp $TMP_DIR
# make log file
LOG_FILE=/tmp/HugeSlackBuilds.log
# clean log file for each run
echo > $LOG_FILE
# repo sources
REPO_SLACKWARE_SOURCE=/opt/slackware-repositories/x86/slackware/slackware64-15.0
REPO_SLACKBUILDS_SOURCE=/opt/slackware-repositories/slackbuilds/15.0
# default verbose
VERBOSE="${VERBOSE:-0}"


## Make HugeSlackBuilds for slackware
# for i in $(grep ".*\.SlackBuild$" /opt/slackware-repositories/x86/slackware/slackware64-15.0/CHECKSUMS.md5 | cut -d" " -f3-) ; do x=$(echo $i | rev | cut -d/ -f2-  | rev | cut -d" " -f3) ; if [ "$(ls /opt/slackware-repositories/x86/slackware/slackware64-15.0/$x/*.SlackBuild | wc -l)" != "1" ] ; then echo $i ; fi   ; done > /tmp/more.than.2.slackbuild

# find SlackBuild files to make HugeSlackBuilds
for slackbuild_line in $(grep ".*\.SlackBuild$" ${REPO_SLACKWARE_SOURCE}/CHECKSUMS.md5 | cut -d" " -f3-) ; do
  #echo "$slackbuild_line"
  slackbuild_path=$(echo $slackbuild_line | rev | cut -d/ -f2-  | rev | cut -d" " -f3)
  VERSION=$(echo $REPO_SLACKWARE_SOURCE | rev | cut -d/ -f1 | rev)
  #echo $VERSION
[[ "$VERBOSE" -eq "0" ]] && \
  echo "[+] Processing ${REPO_SLACKWARE_SOURCE}/$slackbuild_path"
  cd ${REPO_SLACKWARE_SOURCE}/$slackbuild_path || exit 1
[[ "$VERBOSE" -eq "1" ]] && \
  echo -n "cd " &&  pwd
  bash ${CWD}/MakeHugeSlackBuild-0.0.3
done


## Make HugeSlackBuilds for slackbuilds
#
#lrwxrwxrwx 1 root root 44 Jul 28  2023 /var/lib/sbopkg/SBo/15.0 -> /opt/slackware-repositories/slackbuilds/15.0
# ls -la /var/cache/sbopkg/
#
#

